Search.appendIndex(
    [
                {
            "fqsen": "\\rosette\\api\\Address",
            "name": "Address",
            "summary": "Class\u0020that\u0020represents\u0020a\u0020fielded\u0020address.",
            "url": "classes/rosette-api-Address.html"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-Address.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "required\u0020validate\u0020function",
            "url": "classes/rosette-api-Address.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003Afielded\u0028\u0029",
            "name": "fielded",
            "summary": "is\u0020this\u0020a\u0020fielded\u0020address\u003F",
            "url": "classes/rosette-api-Address.html#method_fielded"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024house",
            "name": "house",
            "summary": "The\u0020address\u0020house.",
            "url": "classes/rosette-api-Address.html#property_house"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024houseNumber",
            "name": "houseNumber",
            "summary": "The\u0020address\u0020house\u0020number.",
            "url": "classes/rosette-api-Address.html#property_houseNumber"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024road",
            "name": "road",
            "summary": "The\u0020address\u0020road.",
            "url": "classes/rosette-api-Address.html#property_road"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024unit",
            "name": "unit",
            "summary": "The\u0020address\u0020unit.",
            "url": "classes/rosette-api-Address.html#property_unit"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024level",
            "name": "level",
            "summary": "The\u0020address\u0020level.",
            "url": "classes/rosette-api-Address.html#property_level"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024staircase",
            "name": "staircase",
            "summary": "The\u0020address\u0020staircase.",
            "url": "classes/rosette-api-Address.html#property_staircase"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024entrance",
            "name": "entrance",
            "summary": "The\u0020address\u0020entrance.",
            "url": "classes/rosette-api-Address.html#property_entrance"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024suburb",
            "name": "suburb",
            "summary": "The\u0020address\u0020suburb.",
            "url": "classes/rosette-api-Address.html#property_suburb"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024cityDistrict",
            "name": "cityDistrict",
            "summary": "The\u0020address\u0020city\u0020district.",
            "url": "classes/rosette-api-Address.html#property_cityDistrict"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024city",
            "name": "city",
            "summary": "The\u0020address\u0020city.",
            "url": "classes/rosette-api-Address.html#property_city"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024island",
            "name": "island",
            "summary": "The\u0020address\u0020island.",
            "url": "classes/rosette-api-Address.html#property_island"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024stateDistrict",
            "name": "stateDistrict",
            "summary": "The\u0020address\u0020state\u0020district.",
            "url": "classes/rosette-api-Address.html#property_stateDistrict"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024state",
            "name": "state",
            "summary": "The\u0020address\u0020state.",
            "url": "classes/rosette-api-Address.html#property_state"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024countryRegion",
            "name": "countryRegion",
            "summary": "The\u0020address\u0020country\u0020region.",
            "url": "classes/rosette-api-Address.html#property_countryRegion"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024country",
            "name": "country",
            "summary": "The\u0020address\u0020country.",
            "url": "classes/rosette-api-Address.html#property_country"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024worldRegion",
            "name": "worldRegion",
            "summary": "The\u0020address\u0020world\u0020region.",
            "url": "classes/rosette-api-Address.html#property_worldRegion"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024postCode",
            "name": "postCode",
            "summary": "The\u0020address\u0020post\u0020code.",
            "url": "classes/rosette-api-Address.html#property_postCode"
        },                {
            "fqsen": "\\rosette\\api\\Address\u003A\u003A\u0024poBox",
            "name": "poBox",
            "summary": "The\u0020address\u0020P.O.\u0020Box.",
            "url": "classes/rosette-api-Address.html#property_poBox"
        },                {
            "fqsen": "\\rosette\\api\\AddressSimilarityParameters",
            "name": "AddressSimilarityParameters",
            "summary": "Class\u0020AddressSimilarityParameters.",
            "url": "classes/rosette-api-AddressSimilarityParameters.html"
        },                {
            "fqsen": "\\rosette\\api\\AddressSimilarityParameters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "constructor.",
            "url": "classes/rosette-api-AddressSimilarityParameters.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\AddressSimilarityParameters\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020parameters.",
            "url": "classes/rosette-api-AddressSimilarityParameters.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\AddressSimilarityParameters\u003A\u003A\u0024address1",
            "name": "address1",
            "summary": "",
            "url": "classes/rosette-api-AddressSimilarityParameters.html#property_address1"
        },                {
            "fqsen": "\\rosette\\api\\AddressSimilarityParameters\u003A\u003A\u0024address2",
            "name": "address2",
            "summary": "",
            "url": "classes/rosette-api-AddressSimilarityParameters.html#property_address2"
        },                {
            "fqsen": "\\rosette\\api\\Api",
            "name": "Api",
            "summary": "Class\u0020API.",
            "url": "classes/rosette-api-Api.html"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020an\u0020L\u007BAPI\u007D\u0020object.",
            "url": "classes/rosette-api-Api.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetBindingVersion\u0028\u0029",
            "name": "getBindingVersion",
            "summary": "Returns\u0020the\u0020binding\u0020version",
            "url": "classes/rosette-api-Api.html#method_getBindingVersion"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetUserAgent\u0028\u0029",
            "name": "getUserAgent",
            "summary": "Returns\u0020the\u0020string\u0020used\u0020for\u0020User\u002DAgent",
            "url": "classes/rosette-api-Api.html#method_getUserAgent"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetMockRequest\u0028\u0029",
            "name": "setMockRequest",
            "summary": "Sets\u0020on\u0020override\u0020Request\u0020for\u0020mocking\u0020purposes",
            "url": "classes/rosette-api-Api.html#method_setMockRequest"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetMaxRetries\u0028\u0029",
            "name": "setMaxRetries",
            "summary": "Sets\u0020the\u0020maximum\u0020retries\u0020for\u0020server\u0020connect",
            "url": "classes/rosette-api-Api.html#method_setMaxRetries"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetMillisecondsBetweenRetries\u0028\u0029",
            "name": "setMillisecondsBetweenRetries",
            "summary": "Sets\u0020the\u0020millisecond\u0020sleep\u0020time\u0020between\u0020retries",
            "url": "classes/rosette-api-Api.html#method_setMillisecondsBetweenRetries"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetTimeout\u0028\u0029",
            "name": "setTimeout",
            "summary": "Sets\u0020the\u0020maximum\u0020time\u0020in\u0020seconds\u0020to\u0020wait\u0020for\u0020the\u0020response\u0020to\u0020arrive",
            "url": "classes/rosette-api-Api.html#method_setTimeout"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetResponseCode\u0028\u0029",
            "name": "getResponseCode",
            "summary": "Returns\u0020response\u0020code.",
            "url": "classes/rosette-api-Api.html#method_getResponseCode"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetResponseCode\u0028\u0029",
            "name": "setResponseCode",
            "summary": "Sets\u0020the\u0020response\u0020code.",
            "url": "classes/rosette-api-Api.html#method_setResponseCode"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetDebug\u0028\u0029",
            "name": "setDebug",
            "summary": "Enables\u0020debug\u0020\u0028more\u0020verbose\u0020output\u0029.",
            "url": "classes/rosette-api-Api.html#method_setDebug"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetDebug\u0028\u0029",
            "name": "getDebug",
            "summary": "Retrieves\u0020debug\u0020setting\u0020\u0028more\u0020verbose\u0020output\u0029.",
            "url": "classes/rosette-api-Api.html#method_getDebug"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetServiceUrl\u0028\u0029",
            "name": "getServiceUrl",
            "summary": "Getter\u0020for\u0020the\u0020service_url.",
            "url": "classes/rosette-api-Api.html#method_getServiceUrl"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetServiceUrl\u0028\u0029",
            "name": "setServiceUrl",
            "summary": "Setter\u0020for\u0020the\u0020service_url.",
            "url": "classes/rosette-api-Api.html#method_setServiceUrl"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetUrlParam\u0028\u0029",
            "name": "setUrlParam",
            "summary": "Setter\u0020for\u0020an\u0020additional\u0020query\u0020parameter\u0020to\u0020the\u0020Rosette\u0020API\u0020URL.",
            "url": "classes/rosette-api-Api.html#method_setUrlParam"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetUrlParam\u0028\u0029",
            "name": "getUrlParam",
            "summary": "Getter\u0020for\u0020the\u0020URL\u0020parameter\u0020with\u0020the\u0020specified\u0020name",
            "url": "classes/rosette-api-Api.html#method_getUrlParam"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AclearUrlParams\u0028\u0029",
            "name": "clearUrlParams",
            "summary": "Clears\u0020all\u0020URL\u0020extension\u0020parameters.",
            "url": "classes/rosette-api-Api.html#method_clearUrlParams"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetValueFromArray\u0028\u0029",
            "name": "getValueFromArray",
            "summary": "Gets\u0020the\u0020value\u0020of\u0020the\u0020item\u0020with\u0020key\u0020\u0024name\u0020in\u0020the\u0020array\u0020if\u0020it\u0020exists",
            "url": "classes/rosette-api-Api.html#method_getValueFromArray"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetOption\u0028\u0029",
            "name": "getOption",
            "summary": "Getter\u0020for\u0020options",
            "url": "classes/rosette-api-Api.html#method_getOption"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetOption\u0028\u0029",
            "name": "setOption",
            "summary": "Setter\u0020for\u0020options",
            "url": "classes/rosette-api-Api.html#method_setOption"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AclearOptions\u0028\u0029",
            "name": "clearOptions",
            "summary": "Clears\u0020all\u0020options",
            "url": "classes/rosette-api-Api.html#method_clearOptions"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetCustomHeaders\u0028\u0029",
            "name": "getCustomHeaders",
            "summary": "Setter\u0020for\u0020options",
            "url": "classes/rosette-api-Api.html#method_getCustomHeaders"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsetCustomHeader\u0028\u0029",
            "name": "setCustomHeader",
            "summary": "Setter\u0020for\u0020custom\u0020header",
            "url": "classes/rosette-api-Api.html#method_setCustomHeader"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AaddHeaders\u0028\u0029",
            "name": "addHeaders",
            "summary": "Adds\u0020custom\u0020headers\u0020to\u0020headers\u0020array\u0020if\u0020there\u0020are\u0020any",
            "url": "classes/rosette-api-Api.html#method_addHeaders"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AclearCustomHeaders\u0028\u0029",
            "name": "clearCustomHeaders",
            "summary": "Clears\u0020all\u0020custom\u0020headers",
            "url": "classes/rosette-api-Api.html#method_clearCustomHeaders"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AgetResponseHeader\u0028\u0029",
            "name": "getResponseHeader",
            "summary": "",
            "url": "classes/rosette-api-Api.html#method_getResponseHeader"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AcallEndpoint\u0028\u0029",
            "name": "callEndpoint",
            "summary": "Internal\u0020operations\u0020processor\u0020for\u0020most\u0020of\u0020the\u0020endpoints.",
            "url": "classes/rosette-api-Api.html#method_callEndpoint"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AmakeRequest\u0028\u0029",
            "name": "makeRequest",
            "summary": "function\u0020makeRequest.",
            "url": "classes/rosette-api-Api.html#method_makeRequest"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Aping\u0028\u0029",
            "name": "ping",
            "summary": "Calls\u0020the\u0020Ping\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_ping"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Ainfo\u0028\u0029",
            "name": "info",
            "summary": "Calls\u0020the\u0020info\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_info"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Alanguage\u0028\u0029",
            "name": "language",
            "summary": "Calls\u0020the\u0020language\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_language"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Asentences\u0028\u0029",
            "name": "sentences",
            "summary": "Calls\u0020the\u0020sentences\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_sentences"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Atokens\u0028\u0029",
            "name": "tokens",
            "summary": "Calls\u0020the\u0020tokens\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_tokens"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Amorphology\u0028\u0029",
            "name": "morphology",
            "summary": "Calls\u0020the\u0020morphology\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_morphology"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Aentities\u0028\u0029",
            "name": "entities",
            "summary": "Calls\u0020the\u0020entities\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_entities"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Aevents\u0028\u0029",
            "name": "events",
            "summary": "Calls\u0020the\u0020events\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_events"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Acategories\u0028\u0029",
            "name": "categories",
            "summary": "Calls\u0020the\u0020categories\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_categories"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Asentiment\u0028\u0029",
            "name": "sentiment",
            "summary": "Calls\u0020the\u0020sentiment\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_sentiment"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AnameTranslation\u0028\u0029",
            "name": "nameTranslation",
            "summary": "Calls\u0020the\u0020name\u0020translation\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_nameTranslation"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AnameSimilarity\u0028\u0029",
            "name": "nameSimilarity",
            "summary": "Calls\u0020the\u0020name\u0020similarity\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_nameSimilarity"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AnameDeduplication\u0028\u0029",
            "name": "nameDeduplication",
            "summary": "Calls\u0020the\u0020name\u0020deduplication\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_nameDeduplication"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003ArecordSimilarity\u0028\u0029",
            "name": "recordSimilarity",
            "summary": "Calls\u0020the\u0020record\u0020similarity\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_recordSimilarity"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Arelationships\u0028\u0029",
            "name": "relationships",
            "summary": "Calls\u0020the\u0020relationships\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_relationships"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AtextEmbedding\u0028\u0029",
            "name": "textEmbedding",
            "summary": "Calls\u0020the\u0020text\u002Dembedding\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_textEmbedding"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsemanticVectors\u0028\u0029",
            "name": "semanticVectors",
            "summary": "Calls\u0020the\u0020semantic\u0020vectors\u0020endpoint.",
            "url": "classes/rosette-api-Api.html#method_semanticVectors"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsyntaxDependencies\u0028\u0029",
            "name": "syntaxDependencies",
            "summary": "Calls\u0020the\u0020syntax\/dependencies\u0020endpoint",
            "url": "classes/rosette-api-Api.html#method_syntaxDependencies"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Atransliteration\u0028\u0029",
            "name": "transliteration",
            "summary": "Calls\u0020the\u0020transliteration\u0020endpoint",
            "url": "classes/rosette-api-Api.html#method_transliteration"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003Atopics\u0028\u0029",
            "name": "topics",
            "summary": "Calls\u0020the\u0020topics\u0020endpoint",
            "url": "classes/rosette-api-Api.html#method_topics"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AsimilarTerms\u0028\u0029",
            "name": "similarTerms",
            "summary": "Calls\u0020the\u0020similarTerms\u0020endpoint",
            "url": "classes/rosette-api-Api.html#method_similarTerms"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003AaddressSimilarity\u0028\u0029",
            "name": "addressSimilarity",
            "summary": "Calls\u0020the\u0020addressSimilarity\u0020endpoint",
            "url": "classes/rosette-api-Api.html#method_addressSimilarity"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024binding_version",
            "name": "binding_version",
            "summary": "Compatible\u0020server\u0020version.",
            "url": "classes/rosette-api-Api.html#property_binding_version"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024user_key",
            "name": "user_key",
            "summary": "User\u0020key\u0020\u0028required\u0020for\u0020Rosette\u0020API\u0029.",
            "url": "classes/rosette-api-Api.html#property_user_key"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024service_url",
            "name": "service_url",
            "summary": "URL\u0020of\u0020the\u0020Rosette\u0020API\u0020\u0028or\u0020test\u0020server\u0029.",
            "url": "classes/rosette-api-Api.html#property_service_url"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "HTTP\u0020headers\u0020for\u0020Rosette\u0020API.",
            "url": "classes/rosette-api-Api.html#property_headers"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024url_params",
            "name": "url_params",
            "summary": "Parameters\u0020for\u0020the\u0020URL\u0020query.",
            "url": "classes/rosette-api-Api.html#property_url_params"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024subUrl",
            "name": "subUrl",
            "summary": "Endpoint\u0020for\u0020the\u0020operation.",
            "url": "classes/rosette-api-Api.html#property_subUrl"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024response_code",
            "name": "response_code",
            "summary": "response\u0020code",
            "url": "classes/rosette-api-Api.html#property_response_code"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024options",
            "name": "options",
            "summary": "internal\u0020options\u0020array",
            "url": "classes/rosette-api-Api.html#property_options"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024customHeaders",
            "name": "customHeaders",
            "summary": "internal\u0020customHeaders\u0020array",
            "url": "classes/rosette-api-Api.html#property_customHeaders"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024request",
            "name": "request",
            "summary": "internal\u0020Request\u0020object",
            "url": "classes/rosette-api-Api.html#property_request"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024debug",
            "name": "debug",
            "summary": "More\u0020verbose\u0020output\u0029.",
            "url": "classes/rosette-api-Api.html#property_debug"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024max_retries",
            "name": "max_retries",
            "summary": "The\u0020maximum\u0020retries\u0020for\u0020server\u0020connect",
            "url": "classes/rosette-api-Api.html#property_max_retries"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024ms_between_retries",
            "name": "ms_between_retries",
            "summary": "The\u0020millisecond\u0020sleep\u0020time\u0020between\u0020retries",
            "url": "classes/rosette-api-Api.html#property_ms_between_retries"
        },                {
            "fqsen": "\\rosette\\api\\Api\u003A\u003A\u0024timeout",
            "name": "timeout",
            "summary": "The\u0020maximum\u0020time\u0020in\u0020seconds\u0020to\u0020wait\u0020for\u0020the\u0020response\u0020to\u0020arrive",
            "url": "classes/rosette-api-Api.html#property_timeout"
        },                {
            "fqsen": "\\rosette\\api\\CustomException",
            "name": "CustomException",
            "summary": "Class\u0020CustomException.",
            "url": "classes/rosette-api-CustomException.html"
        },                {
            "fqsen": "\\rosette\\api\\CustomException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-CustomException.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\CustomException\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Magic\u0020method\u0020to\u0020return\u0020the\u0020stringized\u0020form\u0020of\u0020CustomException.",
            "url": "classes/rosette-api-CustomException.html#method___toString"
        },                {
            "fqsen": "\\rosette\\api\\CustomException\u003A\u003A\u0024message",
            "name": "message",
            "summary": "Exception\u0020message.",
            "url": "classes/rosette-api-CustomException.html#property_message"
        },                {
            "fqsen": "\\rosette\\api\\CustomException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "User\u002Ddefined\u0020exception\u0020code.",
            "url": "classes/rosette-api-CustomException.html#property_code"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters",
            "name": "DocumentParameters",
            "summary": "Class\u0020DocumentParameters.",
            "url": "classes/rosette-api-DocumentParameters.html"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-DocumentParameters.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003AsetMultiPartContent\u0028\u0029",
            "name": "setMultiPartContent",
            "summary": "Setter\u0020for\u0020multiPartContent.\u0020Clears\u0020the\u0020content\u0020and\u0020contentUri\u0020properties\u0020if\u0020it\u0020contains\ndata",
            "url": "classes/rosette-api-DocumentParameters.html#method_setMultiPartContent"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003AgetMultiPartContent\u0028\u0029",
            "name": "getMultiPartContent",
            "summary": "Getter\u0020for\u0020multiPartContent",
            "url": "classes/rosette-api-DocumentParameters.html#method_getMultiPartContent"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003AgetFileName\u0028\u0029",
            "name": "getFileName",
            "summary": "Getter\u0020for\u0020fileName",
            "url": "classes/rosette-api-DocumentParameters.html#method_getFileName"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020parameters.",
            "url": "classes/rosette-api-DocumentParameters.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003AloadDocumentFile\u0028\u0029",
            "name": "loadDocumentFile",
            "summary": "Loads\u0020a\u0020file\u0020into\u0020the\u0020object.",
            "url": "classes/rosette-api-DocumentParameters.html#method_loadDocumentFile"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003AloadDocumentString\u0028\u0029",
            "name": "loadDocumentString",
            "summary": "Loads\u0020a\u0020string\u0020into\u0020the\u0020object.",
            "url": "classes/rosette-api-DocumentParameters.html#method_loadDocumentString"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/rosette-api-DocumentParameters.html#property_content"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003A\u0024contentUri",
            "name": "contentUri",
            "summary": "",
            "url": "classes/rosette-api-DocumentParameters.html#property_contentUri"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003A\u0024language",
            "name": "language",
            "summary": "",
            "url": "classes/rosette-api-DocumentParameters.html#property_language"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003A\u0024multiPartContent",
            "name": "multiPartContent",
            "summary": "",
            "url": "classes/rosette-api-DocumentParameters.html#property_multiPartContent"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003A\u0024fileName",
            "name": "fileName",
            "summary": "",
            "url": "classes/rosette-api-DocumentParameters.html#property_fileName"
        },                {
            "fqsen": "\\rosette\\api\\DocumentParameters\u003A\u003A\u0024genre",
            "name": "genre",
            "summary": "",
            "url": "classes/rosette-api-DocumentParameters.html#property_genre"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress",
            "name": "FieldedAddress",
            "summary": "Class\u0020that\u0020represents\u0020an\u0020FieldedAddress.",
            "url": "classes/rosette-api-FieldedAddress.html"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-FieldedAddress.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "required\u0020validate\u0020function",
            "url": "classes/rosette-api-FieldedAddress.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003Afielded\u0028\u0029",
            "name": "fielded",
            "summary": "is\u0020this\u0020a\u0020fielded\u0020address\u003F",
            "url": "classes/rosette-api-FieldedAddress.html#method_fielded"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024house",
            "name": "house",
            "summary": "The\u0020address\u0020house.",
            "url": "classes/rosette-api-FieldedAddress.html#property_house"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024houseNumber",
            "name": "houseNumber",
            "summary": "The\u0020address\u0020house\u0020number.",
            "url": "classes/rosette-api-FieldedAddress.html#property_houseNumber"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024road",
            "name": "road",
            "summary": "The\u0020address\u0020road.",
            "url": "classes/rosette-api-FieldedAddress.html#property_road"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024unit",
            "name": "unit",
            "summary": "The\u0020address\u0020unit.",
            "url": "classes/rosette-api-FieldedAddress.html#property_unit"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024level",
            "name": "level",
            "summary": "The\u0020address\u0020level.",
            "url": "classes/rosette-api-FieldedAddress.html#property_level"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024staircase",
            "name": "staircase",
            "summary": "The\u0020address\u0020staircase.",
            "url": "classes/rosette-api-FieldedAddress.html#property_staircase"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024entrance",
            "name": "entrance",
            "summary": "The\u0020address\u0020entrance.",
            "url": "classes/rosette-api-FieldedAddress.html#property_entrance"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024suburb",
            "name": "suburb",
            "summary": "The\u0020address\u0020suburb.",
            "url": "classes/rosette-api-FieldedAddress.html#property_suburb"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024cityDistrict",
            "name": "cityDistrict",
            "summary": "The\u0020address\u0020city\u0020district.",
            "url": "classes/rosette-api-FieldedAddress.html#property_cityDistrict"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024city",
            "name": "city",
            "summary": "The\u0020address\u0020city.",
            "url": "classes/rosette-api-FieldedAddress.html#property_city"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024island",
            "name": "island",
            "summary": "The\u0020address\u0020island.",
            "url": "classes/rosette-api-FieldedAddress.html#property_island"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024stateDistrict",
            "name": "stateDistrict",
            "summary": "The\u0020address\u0020state\u0020district.",
            "url": "classes/rosette-api-FieldedAddress.html#property_stateDistrict"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024state",
            "name": "state",
            "summary": "The\u0020address\u0020state.",
            "url": "classes/rosette-api-FieldedAddress.html#property_state"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024countryRegion",
            "name": "countryRegion",
            "summary": "The\u0020address\u0020country\u0020region.",
            "url": "classes/rosette-api-FieldedAddress.html#property_countryRegion"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024country",
            "name": "country",
            "summary": "The\u0020address\u0020country.",
            "url": "classes/rosette-api-FieldedAddress.html#property_country"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024worldRegion",
            "name": "worldRegion",
            "summary": "The\u0020address\u0020world\u0020region.",
            "url": "classes/rosette-api-FieldedAddress.html#property_worldRegion"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024postCode",
            "name": "postCode",
            "summary": "The\u0020address\u0020post\u0020code.",
            "url": "classes/rosette-api-FieldedAddress.html#property_postCode"
        },                {
            "fqsen": "\\rosette\\api\\FieldedAddress\u003A\u003A\u0024poBox",
            "name": "poBox",
            "summary": "The\u0020address\u0020P.O.\u0020Box.",
            "url": "classes/rosette-api-FieldedAddress.html#property_poBox"
        },                {
            "fqsen": "\\rosette\\api\\IAddress",
            "name": "IAddress",
            "summary": "Interface\u0020implemented\u0020by\u0020all\u0020Addresses",
            "url": "classes/rosette-api-IAddress.html"
        },                {
            "fqsen": "\\rosette\\api\\IAddress\u003A\u003Afielded\u0028\u0029",
            "name": "fielded",
            "summary": "Returns\u0020whether\u0020or\u0020not\u0020this\u0020address\u0020is\u0020fielded.",
            "url": "classes/rosette-api-IAddress.html#method_fielded"
        },                {
            "fqsen": "\\rosette\\api\\IException",
            "name": "IException",
            "summary": "Interface\u0020IException.",
            "url": "classes/rosette-api-IException.html"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "Returns\u0020the\u0020message\u0020associated\u0020with\u0020the\u0020exception.",
            "url": "classes/rosette-api-IException.html#method_getMessage"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003AgetCode\u0028\u0029",
            "name": "getCode",
            "summary": "Returns\u0020the\u0020code\u0020associated\u0020with\u0020the\u0020exception.",
            "url": "classes/rosette-api-IException.html#method_getCode"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003AgetFile\u0028\u0029",
            "name": "getFile",
            "summary": "Returns\u0020the\u0020file\u0020in\u0020which\u0020the\u0020exception\u0020occurred.",
            "url": "classes/rosette-api-IException.html#method_getFile"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003AgetLine\u0028\u0029",
            "name": "getLine",
            "summary": "Returns\u0020the\u0020line\u0020at\u0020which\u0020the\u0020exception\u0020occurred.",
            "url": "classes/rosette-api-IException.html#method_getLine"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003AgetTrace\u0028\u0029",
            "name": "getTrace",
            "summary": "Returns\u0020a\u0020trace\u0020of\u0020the\u0020exception.",
            "url": "classes/rosette-api-IException.html#method_getTrace"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003AgetTraceAsString\u0028\u0029",
            "name": "getTraceAsString",
            "summary": "Returns\u0020the\u0020trace\u0020in\u0020string\u0020format.",
            "url": "classes/rosette-api-IException.html#method_getTraceAsString"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Override\u0020that\u0020returns\u0020the\u0020string\u0020representation\u0020of\u0020the\u0020exception.",
            "url": "classes/rosette-api-IException.html#method___toString"
        },                {
            "fqsen": "\\rosette\\api\\IException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-IException.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\Name",
            "name": "Name",
            "summary": "Class\u0020that\u0020represents\u0020a\u0020Name.",
            "url": "classes/rosette-api-Name.html"
        },                {
            "fqsen": "\\rosette\\api\\Name\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-Name.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\Name\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "required\u0020validate\u0020function",
            "url": "classes/rosette-api-Name.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\Name\u003A\u003A\u0024text",
            "name": "text",
            "summary": "Textual\u0020form\u0020of\u0020the\u0020name.",
            "url": "classes/rosette-api-Name.html#property_text"
        },                {
            "fqsen": "\\rosette\\api\\Name\u003A\u003A\u0024entityType",
            "name": "entityType",
            "summary": "Entity\u0020type\u0020of\u0020the\u0020name.",
            "url": "classes/rosette-api-Name.html#property_entityType"
        },                {
            "fqsen": "\\rosette\\api\\Name\u003A\u003A\u0024language",
            "name": "language",
            "summary": "Language\u0020of\u0020the\u0020name.",
            "url": "classes/rosette-api-Name.html#property_language"
        },                {
            "fqsen": "\\rosette\\api\\Name\u003A\u003A\u0024script",
            "name": "script",
            "summary": "Script\u0020in\u0020which\u0020the\u0020name\u0020is\u0020written.",
            "url": "classes/rosette-api-Name.html#property_script"
        },                {
            "fqsen": "\\rosette\\api\\NameDeduplicationParameters",
            "name": "NameDeduplicationParameters",
            "summary": "Class\u0020NameDeduplicationParameters.",
            "url": "classes/rosette-api-NameDeduplicationParameters.html"
        },                {
            "fqsen": "\\rosette\\api\\NameDeduplicationParameters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "constructor.",
            "url": "classes/rosette-api-NameDeduplicationParameters.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\NameDeduplicationParameters\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020parameters.",
            "url": "classes/rosette-api-NameDeduplicationParameters.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\NameDeduplicationParameters\u003A\u003A\u0024names",
            "name": "names",
            "summary": "",
            "url": "classes/rosette-api-NameDeduplicationParameters.html#property_names"
        },                {
            "fqsen": "\\rosette\\api\\NameDeduplicationParameters\u003A\u003A\u0024threshold",
            "name": "threshold",
            "summary": "",
            "url": "classes/rosette-api-NameDeduplicationParameters.html#property_threshold"
        },                {
            "fqsen": "\\rosette\\api\\NameSimilarityParameters",
            "name": "NameSimilarityParameters",
            "summary": "Class\u0020NameSimilarityParameters.",
            "url": "classes/rosette-api-NameSimilarityParameters.html"
        },                {
            "fqsen": "\\rosette\\api\\NameSimilarityParameters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "constructor.",
            "url": "classes/rosette-api-NameSimilarityParameters.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\NameSimilarityParameters\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020parameters.",
            "url": "classes/rosette-api-NameSimilarityParameters.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\NameSimilarityParameters\u003A\u003A\u0024name1",
            "name": "name1",
            "summary": "",
            "url": "classes/rosette-api-NameSimilarityParameters.html#property_name1"
        },                {
            "fqsen": "\\rosette\\api\\NameSimilarityParameters\u003A\u003A\u0024name2",
            "name": "name2",
            "summary": "",
            "url": "classes/rosette-api-NameSimilarityParameters.html#property_name2"
        },                {
            "fqsen": "\\rosette\\api\\NameSimilarityParameters\u003A\u003A\u0024genre",
            "name": "genre",
            "summary": "",
            "url": "classes/rosette-api-NameSimilarityParameters.html#property_genre"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters",
            "name": "NameTranslationParameters",
            "summary": "Class\u0020NameTranslationParameters.",
            "url": "classes/rosette-api-NameTranslationParameters.html"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "constructor.",
            "url": "classes/rosette-api-NameTranslationParameters.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020parameters.",
            "url": "classes/rosette-api-NameTranslationParameters.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_name"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024targetLanguage",
            "name": "targetLanguage",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_targetLanguage"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024entityType",
            "name": "entityType",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_entityType"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024sourceLanguageOfOrigin",
            "name": "sourceLanguageOfOrigin",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_sourceLanguageOfOrigin"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024sourceLanguageOfUse",
            "name": "sourceLanguageOfUse",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_sourceLanguageOfUse"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024sourceScript",
            "name": "sourceScript",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_sourceScript"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024targetScript",
            "name": "targetScript",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_targetScript"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024targetScheme",
            "name": "targetScheme",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_targetScheme"
        },                {
            "fqsen": "\\rosette\\api\\NameTranslationParameters\u003A\u003A\u0024genre",
            "name": "genre",
            "summary": "",
            "url": "classes/rosette-api-NameTranslationParameters.html#property_genre"
        },                {
            "fqsen": "\\rosette\\api\\RecordSimilarityParameters",
            "name": "RecordSimilarityParameters",
            "summary": "Class\u0020RecordSimilarityParameters.",
            "url": "classes/rosette-api-RecordSimilarityParameters.html"
        },                {
            "fqsen": "\\rosette\\api\\RecordSimilarityParameters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "constructor",
            "url": "classes/rosette-api-RecordSimilarityParameters.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\RecordSimilarityParameters\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020parameters.",
            "url": "classes/rosette-api-RecordSimilarityParameters.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\RecordSimilarityParameters\u003A\u003A\u0024fields",
            "name": "fields",
            "summary": "",
            "url": "classes/rosette-api-RecordSimilarityParameters.html#property_fields"
        },                {
            "fqsen": "\\rosette\\api\\RecordSimilarityParameters\u003A\u003A\u0024properties",
            "name": "properties",
            "summary": "",
            "url": "classes/rosette-api-RecordSimilarityParameters.html#property_properties"
        },                {
            "fqsen": "\\rosette\\api\\RecordSimilarityParameters\u003A\u003A\u0024records",
            "name": "records",
            "summary": "",
            "url": "classes/rosette-api-RecordSimilarityParameters.html#property_records"
        },                {
            "fqsen": "\\rosette\\api\\RosetteConstants",
            "name": "RosetteConstants",
            "summary": "Class\u0020RosetteConstants.",
            "url": "classes/rosette-api-RosetteConstants.html"
        },                {
            "fqsen": "\\rosette\\api\\RosetteConstants\u003A\u003A\u0024DataFormat",
            "name": "DataFormat",
            "summary": "Accepted\u0020data\u0020formats.",
            "url": "classes/rosette-api-RosetteConstants.html#property_DataFormat"
        },                {
            "fqsen": "\\rosette\\api\\RosetteConstants\u003A\u003A\u0024MorphologyOutput",
            "name": "MorphologyOutput",
            "summary": "Accepted\u0020Morphology\u0020Output\u0020types.",
            "url": "classes/rosette-api-RosetteConstants.html#property_MorphologyOutput"
        },                {
            "fqsen": "\\rosette\\api\\RosetteConstants\u003A\u003A\u0024RosetteExceptionFullClassName",
            "name": "RosetteExceptionFullClassName",
            "summary": "",
            "url": "classes/rosette-api-RosetteConstants.html#property_RosetteExceptionFullClassName"
        },                {
            "fqsen": "\\rosette\\api\\RosetteException",
            "name": "RosetteException",
            "summary": "Class\u0020RosetteException.",
            "url": "classes/rosette-api-RosetteException.html"
        },                {
            "fqsen": "\\rosette\\api\\RosetteException\u003A\u003A\u0024BAD_REQUEST_FORMAT",
            "name": "BAD_REQUEST_FORMAT",
            "summary": "The\u0020general\u0020error\u0020returned\u0020from\u0020Rosette\u0020API,\u0020indicating\u0020unrecognized\u0020format.",
            "url": "classes/rosette-api-RosetteException.html#property_BAD_REQUEST_FORMAT"
        },                {
            "fqsen": "\\rosette\\api\\RosetteException\u003A\u003A\u0024INVALID_DATATYPE",
            "name": "INVALID_DATATYPE",
            "summary": "Internal\u0020error\u0020\u0028api\u0020level\u0029\u0020that\u0020indicates\u0020an\u0020incorrect\u0020datatype.",
            "url": "classes/rosette-api-RosetteException.html#property_INVALID_DATATYPE"
        },                {
            "fqsen": "\\rosette\\api\\RosetteException\u003A\u003A\u0024INCOMPATIBLE_VERSION",
            "name": "INCOMPATIBLE_VERSION",
            "summary": "Internal\u0020error\u0020that\u0020throws\u0020if\u0020the\u0020Rosette\u0020API\u0020server\u0020version\u0020does\u0020not\u0020match\u0020the\u0020Api\u0020version.",
            "url": "classes/rosette-api-RosetteException.html#property_INCOMPATIBLE_VERSION"
        },                {
            "fqsen": "\\rosette\\api\\RosetteException\u003A\u003A\u0024INVALID_PROPERTY_NAME",
            "name": "INVALID_PROPERTY_NAME",
            "summary": "Internal\u0020error\u0020indicating\u0020that\u0020the\u0020requested\u0020property\u0020does\u0020not\u0020exist.",
            "url": "classes/rosette-api-RosetteException.html#property_INVALID_PROPERTY_NAME"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase",
            "name": "RosetteParamsSetBase",
            "summary": "Class\u0020RosetteParamsSetBase.",
            "url": "classes/rosette-api-RosetteParamsSetBase.html"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-RosetteParamsSetBase.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020a\u0020property\u0020based\u0020on\u0020the\u0020name.",
            "url": "classes/rosette-api-RosetteParamsSetBase.html#method_set"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Gets\u0020a\u0020property\u0020value\u0020based\u0020on\u0020the\u0020property\u0020name.",
            "url": "classes/rosette-api-RosetteParamsSetBase.html#method_get"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validates\u0020parameters\u0020before\u0020serializing\u0020them.",
            "url": "classes/rosette-api-RosetteParamsSetBase.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase\u003A\u003AgetMultiPartContent\u0028\u0029",
            "name": "getMultiPartContent",
            "summary": "Provides\u0020default\u0020multiPart\u0020call\u0020for\u0020child\u0020classes\u0020that\u0020don\u0027t\u0020implement\u0020it",
            "url": "classes/rosette-api-RosetteParamsSetBase.html#method_getMultiPartContent"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase\u003A\u003AremoveEmptyProperties\u0028\u0029",
            "name": "removeEmptyProperties",
            "summary": "Recursively\u0020removes\u0020empty\u0020properties\u0020to\u0020facilitate\u0020json\u0020encoding.",
            "url": "classes/rosette-api-RosetteParamsSetBase.html#method_removeEmptyProperties"
        },                {
            "fqsen": "\\rosette\\api\\RosetteParamsSetBase\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020into\u0020a\u0020json\u0020string.",
            "url": "classes/rosette-api-RosetteParamsSetBase.html#method_serialize"
        },                {
            "fqsen": "\\REQUESTS_SILENCE_PSR0_DEPRECATIONS",
            "name": "REQUESTS_SILENCE_PSR0_DEPRECATIONS",
            "summary": "",
            "url": "namespaces/default.html#constant_REQUESTS_SILENCE_PSR0_DEPRECATIONS"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest",
            "name": "RosetteRequest",
            "summary": "Class\u0020RosetteRequest.",
            "url": "classes/rosette-api-RosetteRequest.html"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "class\u0020constructor",
            "url": "classes/rosette-api-RosetteRequest.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "class\u0020destructor",
            "url": "classes/rosette-api-RosetteRequest.html#method___destruct"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003AmakeRequest\u0028\u0029",
            "name": "makeRequest",
            "summary": "Wraps\u0020the\u0020curl\u0020call",
            "url": "classes/rosette-api-RosetteRequest.html#method_makeRequest"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003AgetResponseCode\u0028\u0029",
            "name": "getResponseCode",
            "summary": "Returns\u0020curl\u0020response\u0020code",
            "url": "classes/rosette-api-RosetteRequest.html#method_getResponseCode"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003AgetResponseError\u0028\u0029",
            "name": "getResponseError",
            "summary": "Returns\u0020the\u0020error\u0020string\u0020if\u0020curl\u0020error",
            "url": "classes/rosette-api-RosetteRequest.html#method_getResponseError"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003AgetResponseHeader\u0028\u0029",
            "name": "getResponseHeader",
            "summary": "Returns\u0020the\u0020header\u0020from\u0020the\u0020curl\u0020response",
            "url": "classes/rosette-api-RosetteRequest.html#method_getResponseHeader"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003AgetResponseBody\u0028\u0029",
            "name": "getResponseBody",
            "summary": "Returns\u0020the\u0020body\u0020element\u0020of\u0020the\u0020response\u0020object",
            "url": "classes/rosette-api-RosetteRequest.html#method_getResponseBody"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Returns\u0020the\u0020associative\u0020array\u0020response\u0020or\u0020the\u0020error\u0020message",
            "url": "classes/rosette-api-RosetteRequest.html#method_getResponse"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003AcheckForZip\u0028\u0029",
            "name": "checkForZip",
            "summary": "Checks\u0020for\u0020the\u0020signature\u0020values\u0020of\u0020gzip\u0020and\u0020bzip2",
            "url": "classes/rosette-api-RosetteRequest.html#method_checkForZip"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003A\u0024response",
            "name": "response",
            "summary": "Response\u0020object",
            "url": "classes/rosette-api-RosetteRequest.html#property_response"
        },                {
            "fqsen": "\\rosette\\api\\RosetteRequest\u003A\u003A\u0024initialized",
            "name": "initialized",
            "summary": "indicates\u0020that\u0020curl\u0020is\u0020initialized",
            "url": "classes/rosette-api-RosetteRequest.html#property_initialized"
        },                {
            "fqsen": "\\rosette\\api\\UnfieldedAddress",
            "name": "UnfieldedAddress",
            "summary": "Class\u0020that\u0020represents\u0020an\u0020Address.",
            "url": "classes/rosette-api-UnfieldedAddress.html"
        },                {
            "fqsen": "\\rosette\\api\\UnfieldedAddress\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/rosette-api-UnfieldedAddress.html#method___construct"
        },                {
            "fqsen": "\\rosette\\api\\UnfieldedAddress\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "required\u0020validate\u0020function",
            "url": "classes/rosette-api-UnfieldedAddress.html#method_validate"
        },                {
            "fqsen": "\\rosette\\api\\UnfieldedAddress\u003A\u003Afielded\u0028\u0029",
            "name": "fielded",
            "summary": "is\u0020this\u0020a\u0020fielded\u0020address\u003F",
            "url": "classes/rosette-api-UnfieldedAddress.html#method_fielded"
        },                {
            "fqsen": "\\rosette\\api\\UnfieldedAddress\u003A\u003A\u0024address",
            "name": "address",
            "summary": "The\u0020address",
            "url": "classes/rosette-api-UnfieldedAddress.html#property_address"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\rosette\\api",
            "name": "api",
            "summary": "",
            "url": "namespaces/rosette-api.html"
        },                {
            "fqsen": "\\rosette",
            "name": "rosette",
            "summary": "",
            "url": "namespaces/rosette.html"
        }            ]
);
